version: "3.8"

services:
  nginx:
    image: shinchven/nginx-certbot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-certbot
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/conf.d:/etc/nginx/conf.d
      - ${PWD}/nginx/log:/var/log/nginx
      - ${PWD}/letsencrypt:/etc/letsencrypt
